name: docker-image

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Tag name
        id: tag_name
        run: echo ::set-output name=RELEASE_TAG::${GITHUB_REF/refs\/tags\//}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laserfarm:${{ steps.tag_name.outputs.RELEASE_TAG }},${{ secrets.DOCKERHUB_USERNAME }}/laserfarm:latest