name: build and test

on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        python-version: ['3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: setup-conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: 'conda-forge'
    - run: conda --version
    - run: which python
    - run: conda install pdal python-pdal gdal shapely
    - name: Install the package
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: pip install -e .
    - name: Test with pytest
      env:
        CONDA_PREFIX: /usr/share/miniconda
      run: |
        pip install pytest pytest-cov
        pytest tests --cov=laserfarm --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true